version: "4.0"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: kurganskiyDA-netology-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - kurganskiyDA-my-netology-hw
    restart: always
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway:latest
    container_name: kurganskiyDA-netology-pushgateway
    ports:
      - "9091:9091"
    networks:
      - kurganskiyDA-my-netology-hw
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: kurganskiyDA-netology-grafana
    ports:
      - "80:3000"
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/custom.ini:ro
    networks:
      - kurganskiyDA-my-netology-hw
    restart: always
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  kurganskiyDA-my-netology-hw:
    name: kurganskiyDA-my-netology-hw
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16